[package]
name = "envoluntary"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
regex = "1.12.2"
sha1 = "0.10.6"

[dev-dependencies]
once_cell = "1.21.3"
rusty-fork = "0.3.1"
tempfile = "3.23.0"
